### ISSUE TITLE
Error on /user_events/ custom action

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#390] opened 2020-06-18 18:48 UTC
Trying to retrieve user events (part of the user dashboard) the server just hangs up for a long time. No django error response. Eventually this returned:

![image](https://user-images.githubusercontent.com/6978380/85060136-55104200-b16a-11ea-8794-f915b3aefb14.png)

https://whispersdev.wim.usgs.gov/whispersservices/eventsummaries/user_events/?ordering=-start_date&page=1&page_size=5

**Comment by BlakeDraper** [comment] 2020-06-19 16:59
strangely enough I just _did_ get a response from this endpoint, tho I cannot recreate that success.
![image](https://user-images.githubusercontent.com/6978380/85160066-02935c00-b224-11ea-80f6-4dec223106c3.png)

![image](https://user-images.githubusercontent.com/6978380/85160672-425a4380-b224-11ea-9985-4a50265a0707.png)

 but also note that the request was for a page size of 5 and 21 results returned with this (which may just be the unpaginated response of all of the matches), so not consistent in more ways than one.

**Comment by BlakeDraper** [comment] 2020-06-19 17:01
Tried this exact same request right after using Insomnia and got a 504 gateway timeout after 5 minutes had passed.

**Comment by aaronstephenson** [comment] 2020-06-22 20:58
I've noticed that the django-filters library takes noticeably longer compared to our original filtering code, to handle the exact same request. I think that, combined with the enormous amount of objects that need to be looped over to put together the EventSummary response, is just too much for the server to handle.

I'm not sure what to do. I half tempted to revert this one endpoint to our original filtering, even if that means the automatic API Docs won't show the query params for this endpoint. Tho we could export the schema file and manually add the query params for the API Docs to read...

**Comment by BlakeDraper** [comment] 2020-06-22 21:00
>Tho we could export the schema file and manually add the query params for the API Docs to read...

Let's just do this. This endpoint and the filtering is a critical touchpoint for the client so we really cannot afford for the performance to be compromised. If its easy enough to manually include these params in the docs, seems like an easy decision to me.

**Comment by aaronstephenson** [comment] 2020-06-23 03:09
Turns out the cause of the problem was just a forgotten negation on a logic expression. Fixed in f33af978. Your query example above now takes about 500 ms.

**Closed by aaronstephenson** 2020-06-23 03:09 UTC
Labels: bug
