### ISSUE TITLE
not getting custom/standard notifications

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#349] opened 2020-03-16 20:03 UTC
On Thursday 3/12 I set up standard and custom notifications for new event in a particular state, updated event in a particular state, and an event I was a collaborator on and I didn't get any in-app notifications nor any emails (and I had the email option clicked on).
![image](https://user-images.githubusercontent.com/49287076/76795388-0a5fe200-6797-11ea-9d1c-3d26578ce302.png)

I have step-by-step details of what I did if you want it but it seems to be blanket problem (with Celery Beat?) of notifications not going through so I'll spare you the details unless you want them.

**Comment by aaronstephenson** [comment] 2020-03-20 21:18
This seems to be nothing more than a misconfiguration on my part. I had the celerybeat daemon pointing to a (non-existent) celery.py file in the production directory. I just changed it to point to that file in the test directory. @JChipault let me know how it goes now.

**Comment by JChipault** [comment] 2020-03-20 23:03
Great! I will test this soon!

**Comment by JChipault** [comment] 2020-03-25 12:11
I seem to be getting the standard notifications, but NOT the custom notifications. Yesterday I created 170864, which should have triggered my custom notification of being alerted about events in california and I did not receive a notification via email nor in the website.

**Comment by JChipault** [comment] 2020-03-25 12:20
PS - I turned off all standard notification triggers yesterday so I should have just received a custom notification and did not

**Comment by aaronstephenson** [comment] 2020-03-25 14:40
Thanks. I'll take a look.

**Comment by aaronstephenson** [comment] 2020-03-25 14:47
Ugh. I simply forgot to un-comment the code in the scheduler for custom notifications in the celery.py file. 🤦‍♂ 

This should be working now.

**Comment by JChipault** [comment] 2020-03-26 12:29
I updated event 170864 twice on 3/25, which is an an event in California and with <10 affected, so should have triggered my custom notifications. I didn't get any emails or within-app notifications.

**Comment by aaronstephenson** [comment] 2020-03-26 21:03
OK, this should be fixed now.

I did notice, though, that the values in the "criteria" field are the literal values, that is to say, integer IDs. I will work on substituting the name values instead of the IDs.

**Comment by JChipault** [comment] 2020-03-27 13:57
Getting there... I got custom notifications for two new events created (170866 and 170868) but I was expecting notification for an event that both Lauren and I updated (170864).

**Comment by JChipault** [comment] 2020-03-27 14:14
Also, I don't understand this: "I did notice, though, that the values in the "criteria" field are the literal values, that is to say, integer IDs. I will work on substituting the name values instead of the IDs.", which maybe is irrelevant because it's fixed? But if I'm supposed to be checking for something, I'm not sure what to check for.

**Comment by aaronstephenson** [comment] 2020-03-27 14:23
Not asking you to check anything. I was just trying to make you aware of a related issue that I'm already working on, and thus prevent a bug report.

The issue is that the criteria listed in the email uses IDs instead of names, for example `5` instead of `Alligator`.

**Comment by aaronstephenson** [comment] 2020-03-27 19:26
I found the problem with Event 170864. There was an AttributeError in the notification's message text generation, caused by the code trying to access an attribute that didn't exist on a particular object.

The good news is I am working on scrapping that particular section of code anyway, in my effort to use names instead of IDs. I hope to have the new code up in the test environment later today.

**Comment by aaronstephenson** [comment] 2020-03-27 21:34
Fixed in cbb3ade0

**Comment by JChipault** [comment] 2020-03-31 14:26
Maybe this fix just hasn't been pushed yet??? But I edited 170864 yesterday and did not get a custom notification about it today. I DID get a custom notification for the creation of 170871, which was appropriate. Is it still just an issue with 170864 in particular, or is it that updated events are not triggering a notification?

**Comment by aaronstephenson** [comment] 2020-03-31 15:58
Updates are triggering the notification code. They show up in the logs. The problem was just a mundane TypeError where I was unknowingly trying to concatenate an int to a string. That bug is now fixed in 6b013784.

Thanks for your diligent testing. We just aren't able to test every scenario ourselves and so rely on your SME to try situations we don't think to try.

**Comment by JChipault** [comment] 2020-04-16 19:52
@aaronstephenson I edited 170782 yesterday (marked it as public, added collaborator, added species and number dead) and have 2 different custom notifications set up that changes to this event should have triggered and I did not receive any custom notifications overnight. 

![image](https://user-images.githubusercontent.com/49287076/79500315-dd029000-7ff1-11ea-8c9f-1cffca1156a3.png)

**Comment by aaronstephenson** [comment] 2020-04-16 21:23
Event 170782 has a `modified_date` of October 30, 2019 and a `public` value of False, and its only read user was added October 30, 2019, tho I do see that LocationSpecies 298319, 298311, and 298309 were created/edited.

It's very odd that the edits directly to Event and the EventReadUser didn't seem to save. Do you remember seeing any errors or warnings?

Regardless, the updates/creates to the LocationSpecies should have set the Event modified_date to the edit date. The only thing I can think of is that I had a line of code doing a date comparison to only update the event.modified_date if it was not the same as today's date, and maybe that code wasn't working as intended. So I removed that line to just update the event.modified_date even if it has already been updated that day. Change made in 7c5faaf4 and pushed to test environment.

**Comment by JChipault** [comment] 2020-04-16 22:10
I do not remember seeing any errors. 

I checked the frontend again and it says public and abilene zoo as read/write collaborator (read collaborator already there, i.e. was not added yesterday): 
![image](https://user-images.githubusercontent.com/49287076/79511412-dd585680-8004-11ea-9512-7b75ce849db3.png)

![image](https://user-images.githubusercontent.com/49287076/79511552-1ee90180-8005-11ea-83cc-4db3dab525cc.png)


I'll edit the event again today and report back tomorrow.

**Comment by JChipault** [comment] 2020-04-16 22:12
more data: I received a "Your Events" notification overnight (standard notifications seem to be coming through) that told me that the public field was changed:
![image](https://user-images.githubusercontent.com/49287076/79511705-74bda980-8005-11ea-84c5-cc26275ae78e.png)

**Comment by JChipault** [comment] 2020-04-17 13:17
On 4/16 I added Kim as a read collaborator and added an event diagnosis of botulism suspect to 170872. This should have tripped BOTH my custom notifications and my standard notifications and I received neither this morning.

**Comment by BlakeDraper** [comment] 2020-04-17 14:12
@JChipault I'm looking at your capture of your Custom Notifications, and both include California as one of the parameters. I looked at Event 17082 in the test database and it does not have any event locations in California. That is why you would not receive notifications for those changes -  all criteria of the custom notification trigger must be met to produce the notification.

**Comment by JChipault** [comment] 2020-04-17 14:20
@BlakeDraper Here's 170872... looks like it has california
![image](https://user-images.githubusercontent.com/49287076/79579054-b0e81d00-808c-11ea-8f4b-9623986f700c.png)

**Comment by BlakeDraper** [comment] 2020-04-17 14:26
@JChipault I see the confusion - looks like two digits got transposed. In a comment above you referenced `170782`  so that is what I checked. Note the last 3 digits.

>@aaronstephenson I edited 170782 yesterday (marked it as public, added collaborator, added species and number dead) and have 2 different custom notifications set up that changes to this event should have triggered and I did not receive any custom notifications overnight.

You are correct that `170872` includes Californina. Is `170872` the one you edited?

**Comment by JChipault** [comment] 2020-04-17 14:33
Dang, sorry about that. Yes, it's been 170872 all along

**Comment by BlakeDraper** [comment] 2020-04-17 16:43
@JChipault Ok thanks. We are looking into a cause.

**Comment by JChipault** [comment] 2020-04-17 16:53
To spell it out more, in case it helps you track things down... changing this event on Wednesday triggered a "Your Events" notification but neither of my custom notifications; changing this event Thursday triggered neither my standard notifications (so I lost "Your Events" notification) nor my two custom notifications.

**Comment by aaronstephenson** [comment] 2020-04-17 16:54
I think I have found the cause of the bug, thanks. Will update shortly.

The reason why you were seeing different results those two days was because the back end code was changed several times this week. Hopefully this next update is the ultimate solution.

**Comment by BlakeDraper** [comment] 2020-04-17 19:00
@JChipault you made two changes on 4/16: adding Kim as Event Collaborator and adding an Event Diagnosis of Botulism (suspect).

1) Event Collaborator update is not one of the things we ever designed to trigger an event updated notification. We believe we discussed this issue a while back and the mutually arrived upon conclusion was that only actual event data, i.e. the core tables, i.e. event locations, species, species diagnoses, labs, etc. would trigger. Event Collaborators is more of a peripheral management table than actual event data itself. And there is a realtime notification in place to tell someone they have been added as a Collaborator, so Kim should have received that, but you would not have received anything, by design.

2) You should have received a notification for the updated Event Diagnosis. You didn't because of an error in our code where that particular table was not being checked for changes. That's the fix Aaron references above and that'll be corrected for you shortly. If you had changed another item within the event data, such as species diagnosis for instance, the notification would have come through. Just saying this to explain that it has to do with the specific category of item you updated and not a global problem with notifications. But, its good you did because it uncovered this issue.

**Comment by JChipault** [comment] 2020-04-17 19:14
@BlakeDraper Perfect!

**Comment by aaronstephenson** [comment] 2020-04-21 03:12
I figured it out. It was the 'org' consideration for Custom and All Events Standard Notifications... I had changed the code to use org as the source and the 'consolidator' everywhere except in the code block where I was compiling the updates string, where I was still using user IDs for comparisons (resulting in empty updates strings, which, in the recently refactored code, meant no notifications). Changing that to use org ID when appropriate was the fix.

Please resume testing when you are ready.

**Closed** 2020-08-18 17:38 UTC
