### ISSUE TITLE
Private field data showing in notifications for unauthorized users

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#373] opened 2020-04-28 21:00 UTC
As first reported here: https://github.com/USGS-WiM/whispers/issues/1005

There are private field details coming through in notifications for users who should not have access to those details.

**Comment by aaronstephenson** [comment] 2020-04-30 17:44
I have a solution written, just need to test it.

**Comment by aaronstephenson** [comment] 2020-05-01 21:20
Fixed in 8dc63d1a

**Comment by JChipault** [comment] 2020-05-06 17:11
Seems like a lot of the private fields are appropriately hidden but some are still coming through. In the screenshot below, I'm logged in as neilpartner (organization = Woods Hole) and I can see too many details about an event updated by NWHC. 

1) the location name is tagged on to show that a new location was created but location name is a private field. Couple of options: just state that a location was added and leave it at that? Or use county,state,country instead of location name.
2) location comment made by NWHC was shown to Woods Hole and comments are not public fields

![image](https://user-images.githubusercontent.com/49287076/81207178-c5844a80-8f92-11ea-92ff-a51ef8a49cc0.png)

**Comment by aaronstephenson** [comment] 2020-05-06 18:14
Fixed in 5f68f7b2

Location name substituted with county, state, country.

All new/updated/deleted comments, and contacts, are assessed to determine if the recipient has permission to see them.

**Comment by JChipault** [comment] 2020-05-11 18:05
I did some thorough testing and there are 5 numbered issues noted below amid the text that describes the scenario....


On Sunday 5/10, I added/changed ALL the fields in 170880 from jchipault (NWHC org) account.

When I looked at the notification received by abilene test (Abilene Zoo org), three things slipped through that shouldn't have because they are private fields: (1) Event public changed from false to true (2) Species Diagnosis cause changed from None to Cause of Death and (3) Species Diagnosis basis changed from None to Circumstances such as site history, evidence, and/or clinical signs.

This morning (Monday), I went back to 170880 and changed it to incomplete, not visible to the public, added event org of Wister WMA, added 1 dead red knot, added neilpartner user as read/write collaborator, changed epi to Robert Dusek, changed process status to Supplemental Report Needed, added 4 est sick to the red knot entry.

When I looked at the notification received by neilpartner (Woods Hole org) read/write collaborator, one thing slipped through that shouldn't have because it's an NWHC-only field: (continuing list from above) (4) neilpartner could see the change to Robert Dusek (though, appropriately, not the change to Supplemental Report Needed). 

When I looked at the notification received by abilenetest (Abilene Zoo org), I did not see Robert Dusek or Supplement Report Needed (great!) but since the event was changed to private then (5) this user should not have gotten a notification at all because they are not a collaborator and the event is now private.

Then at 10:30a Monday, I went back to 170880 and changed legal number to 789, added location name of Samson pit, added 1 known sick to the addax, marked complete, marked quality checked.

When I looked at the notification received by neilpartner (Woods Hole org) read/write collaborator, it was as expected. 

When I looked at the notification received by abilenetest (Abilene Zoo org), they did get information about changes made at 10:30a (1 known sick and event marked complete) even though the event was private. See (5) above.

**Comment by aaronstephenson** [comment] 2020-05-12 01:20
Thanks Jenny. So in summary:

- Changing an event from public to private should impose restrictions on notifications
    (Note that this field is not listed in the Business Rules doc)
- Species Diagnosis `cause` and `basis` fields should not be visible to the public
- Event `staff` (aka epi) field should only be visible to NWHC.

I have implemented these changes, and tested them locally in my dev environment and confirmed I am getting the results you expected. Let me know what you see in the test environment.

**Comment by JChipault** [comment] 2020-05-12 15:32
I tried to re-test but did not receive any 10a notifications... maybe they're not running hourly anymore?

**Comment by JChipault** [comment] 2020-05-12 16:07
So I changed 3 events before 10a that were all created by me and had locations in California (170872, 170879, 170880). I did not receive any standard notifications at 10a even though my "Your Events" notification is on. And at 11a I only received 2 notifications (170879, 170880)... so is 170872 acting up again (we had another github ticket about that event, I think)?

**Comment by aaronstephenson** [comment] 2020-05-12 20:55
The problem was a bad query that I introduced yesterday to check permissions for the Species Diagnosis basis and cause fields. I wrote it to use the event ID field of that model, but of course Species Diagnosis doesn't have an event ID. Ugh. So the fix was to just go up the relationship tree to get the parent event ID.

Fixed in ae5d77b4

**Comment by JChipault** [comment] 2020-05-13 20:54
Getting closer.....

170819 was switched from "Not Visible to the Public" to "Visible to the Public" by user jchipault. User abilenetest (who is not a collaborator on this event) got an "All Events" notification with the following:
![image](https://user-images.githubusercontent.com/49287076/81863664-2f6f9780-9531-11ea-83fb-261a4c01c079.pn
![image](https://user-images.githubusercontent.com/49287076/81863683-3696a580-9531-11ea-88c4-5fdc40218e76.png)

Furthermore, when I click on the event while logged in as abilenetest I see this on the event details page for 170819:
![image](https://user-images.githubusercontent.com/49287076/81863797-5e860900-9531-11ea-8f72-a2225296513d.png)

But if I log in as neilpartner (who is a read/write collaborator) I see this with regard to event visibility (which is what I expect to see:
![image](https://user-images.githubusercontent.com/49287076/81863976-98efa600-9531-11ea-87ab-3676ea088158.png)



whereas if I'm logged in as neilpartner (who is a read/write collaborator), I see this:

**Comment by aaronstephenson** [comment] 2020-05-13 21:29
So, this is not a notifications problem.

User abilenetest received the information they were supposed to have received. The problem is that the Event `public` field is not visible to unprivileged users, and it appears that the client relies on that field to show various data. I don't think that field has ever been visible to unprivileged users (the logic being, why show that field to an unprivileged user when the value will always be `True` (such users never being able to see private events anyway).

So, there are two ways to change this behavior: Either unprivileged users get to see the `public` field, or the client application code needs to be changed to not rely on that field.

**Comment by JChipault** [comment] 2020-05-13 21:39
abilenetest is not the event owner, in the event owner's org, or a collaborator on the event so that user should get no notifications if the event is switched from "Not Visible to the Public" to "Visible to the Public" or vice versa because that "Public" field is part of the privileged data. Just like abilenetest shouldn't get a notification if the location name is changed.

**Comment by JChipault** [comment] 2020-05-13 21:41
What's being displayed on the frontend of the Event Details Page was a separate confusing issue to me (not related to notifications, so maybe a better fit for Blake's queue)

**Comment by aaronstephenson** [comment] 2020-05-13 21:47
Ah yes I see now. I will include the `public` field in the permissions check in notifications.

Once again, like most of the issues in the last week or so, we're dealing with a "private" field that is not even listed in the Business Rules spreadsheet. I based most of my notifications field visibility on that doc.

I'll have this fix published shortly.

**Comment by aaronstephenson** [comment] 2020-05-13 21:54
Fixed in 4e159f9e

**Comment by aaronstephenson** [comment] 2020-05-14 16:39
For the client app display issue, I have added a new field in 82ac344b that the client app will use to determine what to show for event details.

**Comment by nbaertlein** [comment] 2020-08-13 20:01
@aaronstephenson I just set up a couple different notifications and made changes to 170865.  Based on update notifications made to accounts, this appears to be working.

**Closed** 2020-08-18 17:04 UTC
Labels: bug
