### ISSUE TITLE
Errors on web api

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices_django#381] opened 2020-05-20 19:18 UTC
I'm getting a little wonkiness with the web services today in both posting and reading data.  The latest has been a TypeError and something not being JSON serializable at https://whisperstest.wim.usgs.gov/whispersservices/userchangerequests/

similar errors presented with https://whisperstest.wim.usgs.gov/whispersservices/organizations/1759/ of which was entered via the database.

**Comment by aaronstephenson** [comment] 2020-05-20 19:42
UserChangeRequest problem fixed by 4e071c8a 

Organization problem is just that org 1759 has a null value for its `created_by` field, which is essential for determining permissions.

**Closed by aaronstephenson** 2020-05-20 19:42 UTC

**Comment by nbaertlein** [comment] 2020-05-21 13:39
@aaronstephenson I'm getting a similar error now when try to post another organization (see pic below).  I was successful posting the following to the live site, but not the test.
{
    "name": "National Park Service - Haleakalā National Park",
    "private_name": "NPS - Haleakalā National Park",
    "address_one": "PO Box 369",
    "city": "Makawao",
    "postal_code": "96768",
    "administrative_level_one": 13,
    "country": 30,
    "phone": "808-572-4400",
    "parent_organization": null,
    "do_not_publish": false,
    "laboratory": false
}

![image](https://user-images.githubusercontent.com/38669574/82564517-82071000-9b3e-11ea-8eb5-3aa9aceea5f4.png)

**Comment by aaronstephenson** [comment] 2020-05-21 14:15
This was caused by a piece of code I added in the last week, that was supposed to act as a last-resort check against an org's parent org being itself, but I forgot to test the situation where the parent org field was null. Fixed in 31901573
