### ISSUE TITLE
is_staff field not present when attempting login

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispersservices_django#387] opened 2020-06-17 15:40 UTC
**Steps to reproduce**: 
1. In client click 'General User' and create a new one
2. Attempt to login with the user you just created 

Client error is caused by the `is_staff` field being 'undefined' instead of false or true.

I'm unsure if this is intentional and the client needs to handle this differently or if `false` should be be set for this field on account creation. 

Response: `{"id":78,"organization_string":"Public","username":"Lauren_test1","first_name":"L","last_name":"Privette","email":"testemail@gmail.com","organization":1}`

![image](https://user-images.githubusercontent.com/23640741/84921370-61c16700-b092-11ea-9312-2756ecc00c25.png)

**Comment by aaronstephenson** [comment] 2020-06-17 19:50
Thanks Lauren. This was caused by the refactored UserSerializer not returning all fields to the /auth endpoint. Fixed in 592058ab

**Closed by aaronstephenson** 2020-06-17 19:50 UTC
